export const users = [
  { id: 1, email: 'user@demo.com', password: 'password123', name: 'Jane Smith', avatar: 'JS' },
  { id: 2, email: 'admin@demo.com', password: 'admin123', name: 'Admin User', avatar: 'AU' },
];

export const categories = [
  { id: 1, slug: 'electronics', name: 'Electronics', icon: '💻', description: 'Gadgets & tech essentials', productCount: 5 },
  { id: 2, slug: 'clothing', name: 'Clothing', icon: '👕', description: 'Fashion for every style', productCount: 5 },
  { id: 3, slug: 'home-kitchen', name: 'Home & Kitchen', icon: '🏠', description: 'Make your space shine', productCount: 5 },
  { id: 4, slug: 'books', name: 'Books', icon: '📚', description: 'Knowledge & stories', productCount: 5 },
  { id: 5, slug: 'sports', name: 'Sports & Outdoors', icon: '🏃', description: 'Stay active, live better', productCount: 5 },
];

export const products = [
  // Electronics
  {
    id: 1,
    name: 'Wireless Noise-Cancelling Headphones',
    price: 79.99,
    originalPrice: 129.99,
    discount: 38,
    category: 'electronics',
    categoryId: 1,
    image: 'https://picsum.photos/seed/headphones01/400/400',
    images: [
      'https://picsum.photos/seed/headphones01/600/600',
      'https://picsum.photos/seed/headphones02/600/600',
      'https://picsum.photos/seed/headphones03/600/600',
    ],
    rating: 4.5,
    reviewCount: 1243,
    stock: 45,
    description: 'Experience immersive sound with our premium wireless headphones. Active noise cancellation blocks out distractions while 30-hour battery life keeps you listening all day. Premium memory foam ear cushions ensure comfort during extended sessions.',
    features: ['Active Noise Cancellation', '30-hour battery life', 'Bluetooth 5.2', 'Foldable design', 'Built-in microphone', 'Quick charge (10 min = 3 hrs)'],
    reviews: [
      { id: 1, user: 'Alex M.', rating: 5, comment: "Best headphones I've ever owned. The ANC is incredible!", date: '2026-03-15' },
      { id: 2, user: 'Sarah K.', rating: 4, comment: 'Great sound quality, very comfortable. Battery lasts forever.', date: '2026-03-10' },
      { id: 3, user: 'Mike R.', rating: 5, comment: 'Worth every penny. Crystal clear calls too.', date: '2026-02-28' },
    ],
    tags: ['wireless', 'audio', 'noise-cancelling'],
    relatedIds: [2, 3, 5],
    featured: true,
    badge: 'Best Seller',
  },
  {
    id: 2,
    name: 'Mechanical Gaming Keyboard',
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    category: 'electronics',
    categoryId: 1,
    image: 'https://picsum.photos/seed/keyboard01/400/400',
    images: [
      'https://picsum.photos/seed/keyboard01/600/600',
      'https://picsum.photos/seed/keyboard02/600/600',
    ],
    rating: 4.7,
    reviewCount: 876,
    stock: 23,
    description: 'Tactile and responsive mechanical switches deliver the ultimate typing experience. Per-key RGB backlighting with 16.8 million colors lets you customize to perfection.',
    features: ['Cherry MX Red switches', 'Per-key RGB backlight', '100% anti-ghosting', 'USB-C braided cable', 'Aluminum top plate', 'N-key rollover'],
    reviews: [
      { id: 1, user: 'Jordan T.', rating: 5, comment: 'Amazing keyboard, the switches feel so satisfying.', date: '2026-04-01' },
      { id: 2, user: 'Chris L.', rating: 4, comment: 'RGB is stunning. Very tactile feedback.', date: '2026-03-20' },
    ],
    tags: ['gaming', 'keyboard', 'mechanical'],
    relatedIds: [1, 3, 4],
    featured: true,
    badge: 'Top Rated',
  },
  {
    id: 3,
    name: '7-in-1 USB-C Hub',
    price: 39.99,
    originalPrice: 59.99,
    discount: 33,
    category: 'electronics',
    categoryId: 1,
    image: 'https://picsum.photos/seed/usbhub01/400/400',
    images: [
      'https://picsum.photos/seed/usbhub01/600/600',
      'https://picsum.photos/seed/usbhub02/600/600',
    ],
    rating: 4.3,
    reviewCount: 542,
    stock: 67,
    description: "Expand your laptop's connectivity with 7 ports in one slim hub. Supports 4K HDMI, 100W Power Delivery, SD card readers, and three USB-A ports.",
    features: ['4K@60Hz HDMI', '100W Power Delivery', 'SD & microSD reader', '3x USB-A 3.0', 'Gigabit Ethernet', 'Compact aluminum body'],
    reviews: [
      { id: 1, user: 'Pat H.', rating: 4, comment: 'Works perfectly with my MacBook. Great build quality.', date: '2026-03-25' },
    ],
    tags: ['usb-c', 'hub', 'connectivity'],
    relatedIds: [1, 2, 4],
    featured: false,
    badge: null,
  },
  {
    id: 4,
    name: 'Smartwatch Pro Series 5',
    price: 149.99,
    originalPrice: 199.99,
    discount: 25,
    category: 'electronics',
    categoryId: 1,
    image: 'https://picsum.photos/seed/smartwatch01/400/400',
    images: [
      'https://picsum.photos/seed/smartwatch01/600/600',
      'https://picsum.photos/seed/smartwatch02/600/600',
      'https://picsum.photos/seed/smartwatch03/600/600',
    ],
    rating: 4.6,
    reviewCount: 2100,
    stock: 12,
    description: 'Track your health, stay connected, and look great doing it. GPS, heart rate monitor, sleep tracking, and 5-day battery life in a premium aluminum chassis.',
    features: ['Built-in GPS', 'Heart rate & SpO2 monitor', 'Sleep tracking', '5-day battery', '50m water resistance', 'Always-on display'],
    reviews: [
      { id: 1, user: 'Emma W.', rating: 5, comment: 'Absolutely love it! The health tracking is so accurate.', date: '2026-04-05' },
      { id: 2, user: 'Liam B.', rating: 5, comment: 'Battery life is incredible. GPS is spot on.', date: '2026-04-02' },
    ],
    tags: ['smartwatch', 'fitness', 'health'],
    relatedIds: [1, 2, 5],
    featured: true,
    badge: 'New Arrival',
  },
  {
    id: 5,
    name: 'True Wireless Earbuds',
    price: 59.99,
    originalPrice: 89.99,
    discount: 33,
    category: 'electronics',
    categoryId: 1,
    image: 'https://picsum.photos/seed/earbuds01/400/400',
    images: [
      'https://picsum.photos/seed/earbuds01/600/600',
      'https://picsum.photos/seed/earbuds02/600/600',
    ],
    rating: 4.4,
    reviewCount: 988,
    stock: 34,
    description: 'Compact, lightweight earbuds with rich bass and crisp highs. IPX5 water resistance makes them perfect for workouts. 6-hour playback + 18 hours from the charging case.',
    features: ['IPX5 water resistant', '6+18 hour battery', 'Touch controls', 'Dual microphone', 'Bluetooth 5.3', 'Compact charging case'],
    reviews: [
      { id: 1, user: 'Nadia S.', rating: 4, comment: 'Sound quality is great for the price. Very comfortable.', date: '2026-03-30' },
    ],
    tags: ['earbuds', 'wireless', 'audio'],
    relatedIds: [1, 2, 4],
    featured: false,
    badge: null,
  },

  // Clothing
  {
    id: 6,
    name: 'Essential Cotton T-Shirt',
    price: 19.99,
    originalPrice: 29.99,
    discount: 33,
    category: 'clothing',
    categoryId: 2,
    image: 'https://picsum.photos/seed/tshirt01/400/400',
    images: [
      'https://picsum.photos/seed/tshirt01/600/600',
      'https://picsum.photos/seed/tshirt02/600/600',
    ],
    rating: 4.2,
    reviewCount: 3210,
    stock: 120,
    description: '100% organic cotton tee that gets softer with every wash. Pre-shrunk and tailored for a comfortable regular fit. Available in 12 colors.',
    features: ['100% organic cotton', 'Pre-shrunk', 'Regular fit', 'Machine washable', 'Available in S–3XL', 'GOTS certified'],
    reviews: [
      { id: 1, user: 'Tom G.', rating: 4, comment: 'Super soft and fits perfectly. Will buy more colors.', date: '2026-04-10' },
    ],
    tags: ['t-shirt', 'cotton', 'casual'],
    relatedIds: [7, 8, 10],
    featured: false,
    badge: null,
  },
  {
    id: 7,
    name: 'Slim Fit Stretch Jeans',
    price: 49.99,
    originalPrice: 79.99,
    discount: 38,
    category: 'clothing',
    categoryId: 2,
    image: 'https://picsum.photos/seed/jeans01/400/400',
    images: [
      'https://picsum.photos/seed/jeans01/600/600',
      'https://picsum.photos/seed/jeans02/600/600',
    ],
    rating: 4.4,
    reviewCount: 1876,
    stock: 56,
    description: 'Modern slim fit jeans crafted from premium stretch denim. Moves with you throughout the day while maintaining a sharp, tailored silhouette.',
    features: ['2% elastane stretch', 'Slim fit', '5-pocket design', 'Machine washable', 'Available in 30–40 waist', 'Premium denim fabric'],
    reviews: [
      { id: 1, user: 'Olivia P.', rating: 5, comment: 'Best fitting jeans I\'ve bought online. Stretchy and flattering.', date: '2026-03-28' },
    ],
    tags: ['jeans', 'denim', 'slim-fit'],
    relatedIds: [6, 8, 9],
    featured: true,
    badge: 'Popular',
  },
  {
    id: 8,
    name: 'Premium Zip-Up Hoodie',
    price: 44.99,
    originalPrice: 69.99,
    discount: 36,
    category: 'clothing',
    categoryId: 2,
    image: 'https://picsum.photos/seed/hoodie01/400/400',
    images: [
      'https://picsum.photos/seed/hoodie01/600/600',
      'https://picsum.photos/seed/hoodie02/600/600',
    ],
    rating: 4.6,
    reviewCount: 2340,
    stock: 78,
    description: 'Cozy fleece-lined hoodie with a durable YKK zipper. Features a kangaroo pocket and adjustable drawstring hood. Perfect for layering in any weather.',
    features: ['80% cotton, 20% polyester', 'Fleece lined', 'YKK zipper', 'Kangaroo pocket', 'Adjustable hood', 'Ribbed cuffs'],
    reviews: [
      { id: 1, user: 'Ben T.', rating: 5, comment: 'So warm and comfortable. The quality is excellent.', date: '2026-04-08' },
    ],
    tags: ['hoodie', 'fleece', 'casual'],
    relatedIds: [6, 7, 10],
    featured: true,
    badge: 'Best Seller',
  },
  {
    id: 9,
    name: 'Lightweight Running Shoes',
    price: 84.99,
    originalPrice: 119.99,
    discount: 29,
    category: 'clothing',
    categoryId: 2,
    image: 'https://picsum.photos/seed/shoes01/400/400',
    images: [
      'https://picsum.photos/seed/shoes01/600/600',
      'https://picsum.photos/seed/shoes02/600/600',
    ],
    rating: 4.5,
    reviewCount: 1654,
    stock: 42,
    description: 'Engineered mesh upper provides breathability while the responsive foam midsole offers cushioning for every stride. Ideal for road running and gym training.',
    features: ['Engineered mesh upper', 'Responsive foam midsole', 'Rubber outsole', 'Breathable lining', 'Sizes US 6–14', 'Reflective details'],
    reviews: [
      { id: 1, user: 'Maya R.', rating: 5, comment: 'Ultra light and so comfortable. Perfect for my morning runs.', date: '2026-04-03' },
    ],
    tags: ['shoes', 'running', 'athletic'],
    relatedIds: [21, 22, 24],
    featured: false,
    badge: null,
  },
  {
    id: 10,
    name: 'Canvas Everyday Backpack',
    price: 54.99,
    originalPrice: 74.99,
    discount: 27,
    category: 'clothing',
    categoryId: 2,
    image: 'https://picsum.photos/seed/backpack01/400/400',
    images: [
      'https://picsum.photos/seed/backpack01/600/600',
      'https://picsum.photos/seed/backpack02/600/600',
    ],
    rating: 4.3,
    reviewCount: 890,
    stock: 31,
    description: 'Sturdy waxed canvas backpack with a 25L capacity. Features a padded laptop sleeve, multiple organizer pockets, and adjustable padded shoulder straps.',
    features: ['Waxed canvas exterior', '25L capacity', '15" laptop sleeve', 'Water resistant', 'USB charging port', 'Padded back panel'],
    reviews: [
      { id: 1, user: 'Anna C.', rating: 4, comment: 'Great quality backpack. Fits my laptop and all my gear easily.', date: '2026-03-22' },
    ],
    tags: ['backpack', 'canvas', 'bag'],
    relatedIds: [6, 7, 8],
    featured: false,
    badge: null,
  },

  // Home & Kitchen
  {
    id: 11,
    name: 'Programmable Coffee Maker',
    price: 69.99,
    originalPrice: 99.99,
    discount: 30,
    category: 'home-kitchen',
    categoryId: 3,
    image: 'https://picsum.photos/seed/coffee01/400/400',
    images: [
      'https://picsum.photos/seed/coffee01/600/600',
      'https://picsum.photos/seed/coffee02/600/600',
    ],
    rating: 4.4,
    reviewCount: 2130,
    stock: 28,
    description: 'Wake up to freshly brewed coffee every morning. Program up to 24 hours in advance with the built-in timer. 12-cup carafe with a keep-warm plate.',
    features: ['12-cup carafe', '24-hr programmable', 'Keep-warm plate', 'Pause & pour', 'Built-in water filter', 'Auto shut-off'],
    reviews: [
      { id: 1, user: 'Rachel G.', rating: 5, comment: 'Makes perfect coffee every time. The auto-brew feature is a game changer.', date: '2026-04-12' },
    ],
    tags: ['coffee', 'kitchen', 'appliance'],
    relatedIds: [12, 13, 15],
    featured: true,
    badge: 'Popular',
  },
  {
    id: 12,
    name: 'Digital Air Fryer 5.8QT',
    price: 89.99,
    originalPrice: 129.99,
    discount: 31,
    category: 'home-kitchen',
    categoryId: 3,
    image: 'https://picsum.photos/seed/airfryer01/400/400',
    images: [
      'https://picsum.photos/seed/airfryer01/600/600',
      'https://picsum.photos/seed/airfryer02/600/600',
    ],
    rating: 4.7,
    reviewCount: 3450,
    stock: 19,
    description: 'Cook crispy, delicious meals with up to 85% less oil. Digital touchscreen with 8 preset cooking modes. Large 5.8QT basket fits a whole chicken.',
    features: ['5.8QT capacity', '8 cooking presets', 'Digital touchscreen', '1750W', 'Dishwasher-safe basket', 'Auto shut-off'],
    reviews: [
      { id: 1, user: 'David K.', rating: 5, comment: 'Best kitchen purchase I\'ve made. Everything comes out crispy and delicious.', date: '2026-04-07' },
    ],
    tags: ['air-fryer', 'kitchen', 'cooking'],
    relatedIds: [11, 13, 14],
    featured: true,
    badge: 'Best Seller',
  },
  {
    id: 13,
    name: "Professional Chef's Knife Set",
    price: 59.99,
    originalPrice: 89.99,
    discount: 33,
    category: 'home-kitchen',
    categoryId: 3,
    image: 'https://picsum.photos/seed/knifeset01/400/400',
    images: [
      'https://picsum.photos/seed/knifeset01/600/600',
      'https://picsum.photos/seed/knifeset02/600/600',
    ],
    rating: 4.5,
    reviewCount: 1120,
    stock: 40,
    description: 'German high-carbon stainless steel 5-piece knife set. Triple-riveted handles for stability. Includes 8" chef knife, bread knife, utility, paring knife, and honing steel.',
    features: ['German high-carbon steel', '5-piece set', 'Triple-riveted handle', 'Balanced weight', 'Dishwasher safe', 'Protective sheaths'],
    reviews: [
      { id: 1, user: 'Chef Mark D.', rating: 5, comment: 'Professional quality at a great price. Sharp right out of the box.', date: '2026-03-19' },
    ],
    tags: ['knife', 'kitchen', 'cooking'],
    relatedIds: [11, 12, 14],
    featured: false,
    badge: null,
  },
  {
    id: 14,
    name: 'Extra-Large Bamboo Cutting Board',
    price: 24.99,
    originalPrice: 34.99,
    discount: 29,
    category: 'home-kitchen',
    categoryId: 3,
    image: 'https://picsum.photos/seed/cuttingboard01/400/400',
    images: [
      'https://picsum.photos/seed/cuttingboard01/600/600',
    ],
    rating: 4.3,
    reviewCount: 780,
    stock: 65,
    description: 'Eco-friendly bamboo cutting board with juice groove and easy-grip handles. Naturally antibacterial and gentle on knife edges. XL size perfect for meal prep.',
    features: ['100% organic bamboo', 'Juice groove', 'Non-slip feet', 'Naturally antibacterial', '18" x 12" size', 'Easy-grip handles'],
    reviews: [
      { id: 1, user: 'Lisa P.', rating: 4, comment: 'Great size for meal prep. Love that it\'s eco-friendly.', date: '2026-04-01' },
    ],
    tags: ['cutting-board', 'bamboo', 'kitchen'],
    relatedIds: [12, 13, 15],
    featured: false,
    badge: null,
  },
  {
    id: 15,
    name: 'Smart Ultrasonic Diffuser',
    price: 34.99,
    originalPrice: 49.99,
    discount: 30,
    category: 'home-kitchen',
    categoryId: 3,
    image: 'https://picsum.photos/seed/diffuser01/400/400',
    images: [
      'https://picsum.photos/seed/diffuser01/600/600',
    ],
    rating: 4.4,
    reviewCount: 620,
    stock: 50,
    description: 'Transform your home with aromatherapy. 500ml tank runs for up to 12 hours. App-controlled with 7 ambient LED color modes and adjustable mist settings.',
    features: ['500ml capacity', '12-hour runtime', 'App control', '7 LED colors', 'Whisper quiet', 'Auto shut-off'],
    reviews: [
      { id: 1, user: 'Sophie L.', rating: 5, comment: 'Makes the whole house smell amazing. The app control is super convenient.', date: '2026-03-31' },
    ],
    tags: ['diffuser', 'aromatherapy', 'home'],
    relatedIds: [11, 13, 14],
    featured: false,
    badge: null,
  },

  // Books
  {
    id: 16,
    name: 'Clean Code',
    price: 34.99,
    originalPrice: 44.99,
    discount: 22,
    category: 'books',
    categoryId: 4,
    image: 'https://picsum.photos/seed/book01/400/400',
    images: ['https://picsum.photos/seed/book01/600/600'],
    rating: 4.8,
    reviewCount: 5600,
    stock: 200,
    description: 'Robert C. Martin\'s classic guide on writing readable, maintainable code. Learn the principles, patterns, and practices of writing clean code that professionals use every day.',
    features: ['464 pages', 'Hardcover & Paperback', 'By Robert C. Martin', 'Publisher: Prentice Hall', 'Best practices & principles', 'Real code examples'],
    reviews: [
      { id: 1, user: 'Dev X.', rating: 5, comment: 'Every software developer should read this. Changed how I write code.', date: '2026-04-10' },
      { id: 2, user: 'Sam K.', rating: 5, comment: 'Timeless. Still relevant after all these years.', date: '2026-03-20' },
    ],
    tags: ['programming', 'software', 'clean-code'],
    relatedIds: [17, 18, 19],
    featured: true,
    badge: 'Must Read',
  },
  {
    id: 17,
    name: 'Atomic Habits',
    price: 16.99,
    originalPrice: 27.99,
    discount: 39,
    category: 'books',
    categoryId: 4,
    image: 'https://picsum.photos/seed/book02/400/400',
    images: ['https://picsum.photos/seed/book02/600/600'],
    rating: 4.9,
    reviewCount: 12300,
    stock: 150,
    description: 'James Clear\'s #1 New York Times bestseller on building good habits and breaking bad ones. Practical strategies backed by science to help you achieve remarkable results.',
    features: ['320 pages', 'Paperback & Hardcover', 'By James Clear', '#1 NYT Bestseller', 'Actionable framework', 'Science-based methods'],
    reviews: [
      { id: 1, user: 'Priya M.', rating: 5, comment: 'Life-changing book. The 1% improvement concept is incredibly powerful.', date: '2026-04-08' },
    ],
    tags: ['self-help', 'habits', 'productivity'],
    relatedIds: [16, 19, 20],
    featured: true,
    badge: '#1 Bestseller',
  },
  {
    id: 18,
    name: 'The Pragmatic Programmer',
    price: 39.99,
    originalPrice: 49.99,
    discount: 20,
    category: 'books',
    categoryId: 4,
    image: 'https://picsum.photos/seed/book03/400/400',
    images: ['https://picsum.photos/seed/book03/600/600'],
    rating: 4.7,
    reviewCount: 4100,
    stock: 80,
    description: '20th Anniversary Edition. This influential book examines the core process of software development — from personal responsibility to career development to architecture.',
    features: ['352 pages', 'Paperback', 'By Hunt & Thomas', '20th Anniversary Ed.', 'Classic reference', 'Updated for modern dev'],
    reviews: [
      { id: 1, user: 'Jake R.', rating: 5, comment: 'A must-have for any serious developer. Timeless wisdom.', date: '2026-03-14' },
    ],
    tags: ['programming', 'software-engineering', 'career'],
    relatedIds: [16, 17, 19],
    featured: false,
    badge: null,
  },
  {
    id: 19,
    name: 'Design Patterns: GoF',
    price: 44.99,
    originalPrice: 54.99,
    discount: 18,
    category: 'books',
    categoryId: 4,
    image: 'https://picsum.photos/seed/book04/400/400',
    images: ['https://picsum.photos/seed/book04/600/600'],
    rating: 4.6,
    reviewCount: 3200,
    stock: 60,
    description: 'The definitive guide to design patterns by the Gang of Four. Covers 23 essential patterns for object-oriented software design that every developer should know.',
    features: ['395 pages', 'Hardcover', 'Gang of Four', '23 classic patterns', 'UML diagrams', 'Language-agnostic'],
    reviews: [
      { id: 1, user: 'Kim L.', rating: 5, comment: 'The bible of software design. Essential reading.', date: '2026-02-20' },
    ],
    tags: ['programming', 'design-patterns', 'architecture'],
    relatedIds: [16, 17, 18],
    featured: false,
    badge: null,
  },
  {
    id: 20,
    name: 'Deep Work',
    price: 14.99,
    originalPrice: 24.99,
    discount: 40,
    category: 'books',
    categoryId: 4,
    image: 'https://picsum.photos/seed/book05/400/400',
    images: ['https://picsum.photos/seed/book05/600/600'],
    rating: 4.6,
    reviewCount: 7800,
    stock: 130,
    description: 'Cal Newport\'s guide to cultivating the ability to focus without distraction on cognitively demanding tasks. Develop the skills to thrive in the knowledge economy.',
    features: ['304 pages', 'Paperback', 'By Cal Newport', 'Productivity focused', 'Actionable strategies', 'Wall Street Journal Bestseller'],
    reviews: [
      { id: 1, user: 'Noah W.', rating: 5, comment: 'Changed how I work completely. No more shallow distractions.', date: '2026-04-05' },
    ],
    tags: ['productivity', 'focus', 'self-help'],
    relatedIds: [17, 18, 19],
    featured: false,
    badge: null,
  },

  // Sports
  {
    id: 21,
    name: 'Premium Non-Slip Yoga Mat',
    price: 39.99,
    originalPrice: 59.99,
    discount: 33,
    category: 'sports',
    categoryId: 5,
    image: 'https://picsum.photos/seed/yogamat01/400/400',
    images: [
      'https://picsum.photos/seed/yogamat01/600/600',
      'https://picsum.photos/seed/yogamat02/600/600',
    ],
    rating: 4.6,
    reviewCount: 2340,
    stock: 55,
    description: '6mm thick TPE yoga mat with superior grip and cushioning. Eco-friendly, free from harmful chemicals. Alignment lines help perfect your posture.',
    features: ['6mm thick TPE foam', 'Alignment lines', 'Non-slip surface', 'Eco-friendly', 'Carrying strap included', '183cm x 61cm'],
    reviews: [
      { id: 1, user: 'Lily Z.', rating: 5, comment: 'Great grip even when sweaty. Love the alignment guides.', date: '2026-04-11' },
    ],
    tags: ['yoga', 'fitness', 'mat'],
    relatedIds: [22, 23, 25],
    featured: false,
    badge: null,
  },
  {
    id: 22,
    name: 'Resistance Bands Set (5 Levels)',
    price: 24.99,
    originalPrice: 39.99,
    discount: 38,
    category: 'sports',
    categoryId: 5,
    image: 'https://picsum.photos/seed/bands01/400/400',
    images: ['https://picsum.photos/seed/bands01/600/600'],
    rating: 4.5,
    reviewCount: 1890,
    stock: 90,
    description: 'Set of 5 color-coded latex resistance bands from 10 to 50 lbs resistance. Perfect for home workouts, physical therapy, and progressive training.',
    features: ['5 resistance levels', '10–50 lbs range', 'Natural latex', 'Stackable rings', 'Carry bag included', 'Door anchor & handles'],
    reviews: [
      { id: 1, user: 'Ryan D.', rating: 5, comment: 'Great for home workouts. Replaced my gym membership!', date: '2026-04-06' },
    ],
    tags: ['resistance-bands', 'fitness', 'home-gym'],
    relatedIds: [21, 24, 25],
    featured: true,
    badge: 'Popular',
  },
  {
    id: 23,
    name: 'Insulated Stainless Water Bottle',
    price: 29.99,
    originalPrice: 44.99,
    discount: 33,
    category: 'sports',
    categoryId: 5,
    image: 'https://picsum.photos/seed/bottle01/400/400',
    images: ['https://picsum.photos/seed/bottle01/600/600'],
    rating: 4.7,
    reviewCount: 4200,
    stock: 88,
    description: 'Double-wall vacuum insulation keeps drinks cold 24 hours or hot 12 hours. 32oz capacity with a leak-proof lid. BPA-free stainless steel.',
    features: ['32oz / 950ml', 'Double-wall vacuum', 'Cold 24hr / Hot 12hr', 'BPA-free steel', 'Leak-proof lid', 'Wide mouth'],
    reviews: [
      { id: 1, user: 'Mia F.', rating: 5, comment: 'My coffee stays hot all morning. The quality is outstanding.', date: '2026-04-09' },
    ],
    tags: ['water-bottle', 'hydration', 'fitness'],
    relatedIds: [21, 22, 25],
    featured: false,
    badge: null,
  },
  {
    id: 24,
    name: 'Speed Jump Rope Pro',
    price: 19.99,
    originalPrice: 29.99,
    discount: 33,
    category: 'sports',
    categoryId: 5,
    image: 'https://picsum.photos/seed/jumprope01/400/400',
    images: ['https://picsum.photos/seed/jumprope01/600/600'],
    rating: 4.4,
    reviewCount: 1100,
    stock: 75,
    description: 'Lightweight speed rope with 360° swivel bearings for smooth, tangle-free rotation. Adjustable length fits all heights. Memory foam handles absorb impact.',
    features: ['360° swivel bearing', 'Adjustable length', 'Memory foam handles', 'Steel wire cable', 'Counter & timer', '2 extra cables'],
    reviews: [
      { id: 1, user: 'Carlos M.', rating: 4, comment: 'Very fast rope. Great for double-unders. No tangles!', date: '2026-03-18' },
    ],
    tags: ['jump-rope', 'cardio', 'fitness'],
    relatedIds: [21, 22, 25],
    featured: false,
    badge: null,
  },
  {
    id: 25,
    name: 'High-Density Foam Roller',
    price: 27.99,
    originalPrice: 39.99,
    discount: 30,
    category: 'sports',
    categoryId: 5,
    image: 'https://picsum.photos/seed/foamroller01/400/400',
    images: ['https://picsum.photos/seed/foamroller01/600/600'],
    rating: 4.5,
    reviewCount: 1560,
    stock: 43,
    description: 'High-density EVA foam roller for deep tissue massage and muscle recovery. Firm surface provides intense myofascial release. Perfect pre/post workout.',
    features: ['High-density EVA', '36" x 6" size', 'Textured surface', '500 lb capacity', 'Hollow core', 'Instructional guide'],
    reviews: [
      { id: 1, user: 'Tina L.', rating: 5, comment: 'Really helps with muscle soreness. A must for recovery.', date: '2026-04-04' },
    ],
    tags: ['foam-roller', 'recovery', 'fitness'],
    relatedIds: [21, 22, 24],
    featured: false,
    badge: null,
  },
];
